FROM centos:centos6

ADD AMON_RPM_FILE var/agent.rpm

RUN curl -L https://github.com/aelsabbahy/goss/releases/download/v0.1.3/goss-linux-amd64 > /usr/local/bin/goss && chmod +rx /usr/local/bin/goss


RUN yum -y install /var/agent.rpm

RUN goss validate
RUN yum remove -y amonagent
